basket/urls.py
from django.urls import path

from . import views


app_name = 'basket'
urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all ,name='product_all'),
    path('<slug:slug>', views.product_detail ,name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list ,name='category_list'),

]

basket/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)


    class Meta:
        verbose_name_plural = 'categories'


    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

 
    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='product_creator', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/default.jpg')
    slug = models.SlugField(max_length=255)
    price =  models.DecimalField(max_digits=6, decimal_places=2)
    is_active = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()


    class Meta:
        ordering = ('-created', )
        

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])


    def __str__(self):
        return self.title

basket/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from .basket import Basket

from store.models import Product


def basket_summary(request):
    basket = Basket(request)
    return render(request, 'store/basket/summary.html', { 'basket': basket })


def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, quantity=product_qty)
        basket_qty = basket.__len__()
        response = JsonResponse({'quantity': basket_qty})
        return response

def basket_delete(request):
    basket = Basket(request)

    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product_id=product_id)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'quantity': basketqty, 'subtotal': baskettotal})
        return response

def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        basket.update(product_id=product_id, quantity=product_qty)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'quantity': basketqty, 'subtotal': baskettotal})
        return response

store/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product


def product_all(request):
    # select the products are currently active
    products = Product.products.all()
    return render(request, 'store/home.html', {'products': products})

def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/products/detail.html', {'product': product})

def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products':products})

templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css"
      integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.6.3.min.js"
      integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU="
      crossorigin="anonymous"
    ></script>
    <title>{% block title %}BookStore{% endblock %}</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">BookStore</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Category
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li>
                    <a
                      class="dropdown-item"
                      href="{% url 'store:product_all' %}"
                      >All</a
                    >
                  </li>
                  {% for c in categories %}
                  <li>
                    <a class="dropdown-item" href="{{c.get_absolute_url}}"
                      >{{c.name|title}}</a
                    >
                  </li>
                  {% endfor %}
                </ul>
              </li>
            </ul>

            <a
              class="btn btn-outline-secondary"
              href="{% url 'basket:basket_summary'%}"
              role="button"
            >
              {% with total_qty=basket|length %}
                <div id="basket-qty" class="d-inline-flex">
                  {% if total_qty > 0 %}
                    {{total_qty}}
                  {% else %}
                    0
                  {% endif %}
                </div>
              {% endwith %}

              <i class="bi bi-cart3"></i>
              Basket
            </a>
          </div>
        </div>
      </nav>
    </header>
    <div id="content">{% block content %}{% endblock %}</div>

    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
      integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
      integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/store/basket/summary.html
{% extends "../base.html" %} {% load static %} {% block title %}Basket
Summary{%endblock %} {% block content %}

<main class="pt-5">
  <div class="container">
    <h1 class="h5">Shopping Basket</h1>
    {% for item in basket %} {% with product=item.product %}
    <div data-index="{{product.id}}" class="row mb-4 border product-item">
      <div class="col-md-3 col-lg-2 order-md-first bg-light">
        <img
          class="img-fluid mx-auto d-block"
          width="120px"
          alt="Responsive image"
          src="{{ product.image.url }}"
        />
      </div>
      <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
        <a
          href="{{ product.get_absolute_url }}"
          class="text-decoration-none text-reset"
        >
          <h1 class="h5 pt-2">{{ product.title }}</h1>
        </a>
        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">
              <div class="col-6">Hardback Book</div>
              <div class="col-6 text-end">
                <span class="h6 fw-bold">£{{ product.price }}</span>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="row p-3">
              <div class="col-12">
                <label for="select">Qty</label>
                <select id="select{{product.id}}">
                  <option selected>{{item.quantity}}</option>
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                </select>
                <button
                  type="button"
                  id="update-button"
                  data-index="{{product.id}}"
                  class="btn btn-outline-secondary btn-sm update-button"
                >
                  Update
                </button>
                <button
                  type="button"
                  id="delete-button"
                  data-index="{{product.id}}"
                  class="btn btn-outline-secondary btn-sm delete-button"
                >
                  Delete
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endwith %} {% endfor %}
    <div class="col-12 text-end">
      <div class="h6 fw-bold">
        Sub Total:
        <span id="subtotal" class="d-inline-flex"
          >{{basket.get_total_price}}</span
        >
      </div>
    </div>
  </div>
</main>
<script>
  // delete item
  $(document).on('click', '.delete-button', function(e){
      e.preventDefault();
      var prodid = $(this).data('index');
      $.ajax({
          type: 'POST',
          url: '{% url "basket:basket_delete" %}',
          data: {
              productid: $(this).data('index'),
              csrfmiddlewaretoken: "{{csrf_token}}",
              action: 'post'
          },
          success: function (json) {
            $('.product-item[data-index="'+ prodid +'"]').remove()
            document.getElementById("basket-qty").innerHTML = json.quantity
            document.getElementById("subtotal").innerHTML = json.subtotal
          },
          error: function (xhr, erro_message, error) {}
      });
  })

  // update item
  $(document).on('click', '.update-button', function(e){
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
        type: 'POST',
        url: '{% url "basket:basket_update" %}',
        data: {
            productid: $(this).data('index'),
            productqty: $('#select' + prodid + ' option:selected').text(),
            csrfmiddlewaretoken: "{{csrf_token}}",
            action: 'post'
        },
        success: function (json) {
          document.getElementById("basket-qty").innerHTML = json.quantity
          document.getElementById("subtotal").innerHTML = json.subtotal
        },
        error: function (xhr, erro_message, error) {}
    });
})
</script>
{% endblock %}

templates/store/home.html
{% extends './base.html' %}
{% block title %}BookStore{% endblock %}
{% block content %}
<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-3">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Album example</h1>
                <p class="lead text-muted">Something short and leading about the collection below—its contents, the
                    creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it
                    entirely.</p>
                <p>
                    <a href="#" class="btn btn-primary my-2">Main call to action</a>
                    <a href="#" class="btn btn-secondary my-2">Secondary action</a>
                </p>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            <div class="pb-3 h5">All Books</div>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    
                {% for product in products %}
                <div class="col">
                    <div class="card shadow-sm">
                        <img class="img-fluid" src="{{product.image.url}}" alt="Responsive Image">
                        <div class="card-body">
                            <p class="card-text">
                                <a href="{{ product.get_absolute_url }}" class="text-dark text-decoration-none">{{product.title}}</a>
                            </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">9 mins</small>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

</main>
{% endblock %}

templates/store/products/category.html
{% extends '../base.html' %}
{% block title %}
{% if category %} {{category.name}} {% else %}Products{% endif %}
{% endblock %}
{% block content %}
<main>

    <div class="album py-5 bg-light">
        <div class="container">
            <div class="pb-3 h5">{{ category.name|title }}</div>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    
                {% for product in products %}
                <div class="col">
                    <div class="card shadow-sm">
                        <img class="img-fluid" src="{{product.image.url}}" alt="Responsive Image">
                        <div class="card-body">
                            <p class="card-text">
                                <a href="{{ product.get_absolute_url }}" class="text-dark text-decoration-none">{{product.title}}</a>
                            </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">9 mins</small>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

</main>
{% endblock %}

templates/store/products/detail.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
  {{ product.name }}
{% endblock %}
{% block content %}
<div class="container">
  <main class="pt-5">
    <div class="row g-3">
      <div class="col-md-5 col-lg-5 order-md-first bg-light">
        <img
          class="img-fluid mx-auto d-block"
          width="200px"
          alt="Responsive image"
          src="{{ product.image.url }}"
        />
      </div>
      <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
        <h1 class="mb-0 h4">{{ product.title }}</h1>
        <p><span class="lead">{{ product.author }}</span> (Author)</p>
        <p>{{ product.description|slice:":355" }}...</p>
        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">
              <div class="col-6">Hardback</div>
              <div class="col-6 text-end">
                <span class="h4 fw-bold">£{{ product.price }}</span>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="row p-3">
              <div class="col-6">
                <label for="select">Qty</label>
                <select id="select">
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                </select>
              </div>
              <div class="col-6 text-end">
                <button type="button" id="add-item" value="{{product.id}}" class="btn btn-secondary btn-sm">
                  Add to basket
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>

<script>
    $(document).on('click', '#add-item', function(e){
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productid: $('#add-item').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
              console.log(json)
              document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, erro_message, error) {}
        });
    })
</script>
{% endblock %}